name: muni-crawlers
channels:
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - ncurses
  - openssl
  - pip
  - python=3.11
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - anyio
      - bandit
      - certifi
      - click
      - greenlet
      - h11
      - httpcore
      - httpx
      - idna
      - markdown-it-py
      - mccabe
      - mdurl
      - mypy
      - mypy-extensions
      - packaging
      - pathspec
      - pbr
      - platformdirs
      - playwright
      - playwright-stealth
      - pycodestyle
      - pyee
      - pyflakes
      - pygments
      - pyyaml
      - rich
      - sniffio
      - stevedore
      - typing-extensions
